server:
  port: 80

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 3
            minimumNumberOfCalls: 3
            permittedNumberOfCallsInHalfOpenState: 2
            failureRateThreshold: 50
            slowCallDurationThreshold: 1s
            slowCallRateThreshold: 50
            record-exceptions:
              - com.demoresilience4j.service.exception.PaymentException
            ignore-exceptions:
              - com.demoresilience4j.service.exception.PaymentIgnoredException
    instances:
        flexPayment:
            baseConfig: default

spring:
  jackson:
    serialization:
      indent-output: true

  
