server:
  port: 80

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 6
            minimumNumberOfCalls: 6
            permittedNumberOfCallsInHalfOpenState: 3
            failureRateThreshold: 50
            slowCallDurationThreshold: 2s
            slowCallRateThreshold: 70
            ignore-exceptions:
                - com.demoresilience4j.service.exception.PaymentException
    instances:
        flexPayment:
            baseConfig: default

spring:
  jackson:
    serialization:
      indent-output: true

  
